// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKLV54uzJ3Ox5fwZbG7DqyzrXBDCzZMVI',
    appId: '1:518238869856:web:2c5eb92b3239ba962c2605',
    messagingSenderId: '518238869856',
    projectId: 'ftest-firebase',
    authDomain: 'ftest-firebase.firebaseapp.com',
    storageBucket: 'ftest-firebase.firebasestorage.app',
    measurementId: 'G-2003HFSSFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm1xUyhvHNxEJ1k_Cs_7c4OWjUztslCi8',
    appId: '1:518238869856:android:6bc6ffbb225ce9222c2605',
    messagingSenderId: '518238869856',
    projectId: 'ftest-firebase',
    storageBucket: 'ftest-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCUKFe0ebMHj4p4rQ6zGhRdPttSp9iIpY',
    appId: '1:518238869856:ios:35759628edc74a412c2605',
    messagingSenderId: '518238869856',
    projectId: 'ftest-firebase',
    storageBucket: 'ftest-firebase.firebasestorage.app',
    iosBundleId: 'com.example.shopping.shoppingCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCUKFe0ebMHj4p4rQ6zGhRdPttSp9iIpY',
    appId: '1:518238869856:ios:35759628edc74a412c2605',
    messagingSenderId: '518238869856',
    projectId: 'ftest-firebase',
    storageBucket: 'ftest-firebase.firebasestorage.app',
    iosBundleId: 'com.example.shopping.shoppingCart',
  );

}